### ISSUE TITLE
Bundler Plugin System

### ISSUE THREAD

**Issue by maclover7** [bundler/bundler#3463]
This was discussed in [bundler/bundler-features#8](https://github.com/bundler/bundler-features#8) and also in #1945. I am suggesting that we go with a combination of what Heroku and Vagrant have done for their plugin ecosystem.
# Part 1: Installation/Storage/Activation
- [ ] Plugins are packaged as gems following the convention: bundler-[plugin name]
# Part 2: Usage
- [ ] Plugins can run executables
  - [ ] Provide an API/base class for CLI plugins to inherit from
- [ ] Plugins can do things/run tasks after Bundler does something
  - [ ] [Provide some sort of hook system/notifier/thing for plugins to latch onto](https://trello.com/c/LJUJNMGN/73-add-lifecycle-hooks)
# Part 3: Decisions
## \- [ ] Declaring plugins

In the Gemfile there are a few options about how one could say "I want to use the gem 'bundler-svn'"
~~\- Option 1:~~

``` shell
gem "bundler-svn"
```

~~Pro: Super easy syntax. Makes sense.~~
~~Con: Not really any cons.~~

~~\- Option 2:~~

``` shell
group :plugins do
  gem "bundler-svn"
end
```

~~Pro: Easier to parse than trying to ask each gem: "Do you have the prefix 'bundler-'"~~
~~Pro: Easier to see what plugins you have, they are all next to each other.~~
~~Con: Maybe some people don't want a separate group for plugins?~~
- Option 3:

``` shell
plugin "svn"
```

Pro: Even easier syntax than option 1.
Con: Requires some special wiring through Bundler to support.
Con: Either way the 'bundler-' gem prefix will be applied, makes no difference.
## \- [ ] Plugins at the User or Project levels

Some plugins may need to be loaded at the user level. For example, someone may want to install a svn plugin, and be able to use svn on all projects. I think we need to be consistent across all 3 plugin subtypes about this policy - subcommands, hooks, and source hooks (svn, hg)
- Option 1: Have all plugins be available at the user level
- Option 2: Have all plugins be available at the project level. This will require everything to be included in the Gemfile manifest.
## \- [ ] Plugin Dependencies
- If your plugin had any dependencies, you must vendor them within the gem. Documentation will be coming out explaining how to do this.

**Comment by andremedeiros** [comment]
I'd say that a con to Part 3, Option 1 would be that we would have to forcefully satisfy that dependency before any others. In that case, without the plugin already activated, we can't satisfy a gem that needs to be checkout from SVN. Same goes for Option 2, but it's slightly easier to just get that group first.

**Comment by segiddins** [comment]
My vote is for Part 3, Option 3.

**Comment by maclover7** [comment]
I'm a fan of Option 2. It seems easier to me to implement than Option 3, also, either way the 'bundler-' prefix has to be applied. I do understand the minimalistic sense of Option 3, but it would seem more difficult to me to have to add another quality to the Gemfile and then have to spread that change across Bundler.

**Comment by maclover7** [comment]
Once we have decided, I'm happy to start a PR for this. cc @indirect

**Comment by indirect** [comment]
I'm pretty sure that it's actually going to be easier to implement option 3 than option 2. We'll need to load plugins before loading the rest of the Gemfile, and a dedicated plugin method makes it easier to get just plugins first and then everything else after.

**Comment by sheerun** [comment]
I like Option 3. It's more explicit. And it makes `bundle install` fail on non-supported bundler version.

**Comment by andremedeiros** [comment]
As for what level plugins are installed, we need both, which is why discoverability is paramount.

For instance, `bundle gem` should really be a plugin, and that's never going to be a project plugin. That's the plugin that creates them.

**Comment by TimMoore** [comment]
For `bundle gem`, it seems like a bit of a special case. Does it even need to interface with the rest of Bundler? To me, it seems like a completely separate tool, unrelated to the rest of what Bundler does.

**Comment by andremedeiros** [comment]
You're 100% right, @TimMoore. In fact, it could probably be built today with the executable lookup. But how about `bundle pristine` or `bundle open`? Would you want to have those project-wide or user-wide?

(Just trying to cover all angles here)

**Comment by TimMoore** [comment]
Good point, @andremedeiros. I think it depends on the type of the plugin:

- Sub-commands shouldn't need to be configured at all IMO if they're running as a child process. If you run a sub-command, it should just search your `PATH`. You could install with `gem install` or any other mechanism. If you want everyone in the project to use it, it can just be a normal `gem` dependency.
- SCM plugins need to be in the `Gemfile`. I don't think there's any need to have these installed at the user level. Each `Gemfile` either uses it or doesn't. I can't think of a reason to use one outside the context of a project.
- Post-install hooks I could see going either way, so we might need both user-level and project-level for those. Like if you wanted to have a hook that installs docs or regenerates ctags, that's probably a user-level thing. In other cases, your project might depend on particular hooks running after install, for example if you need to clear a cache or run a code generator.

**Comment by ph** [comment]
I was wondering, it is planned to create hooks for existing command?
Like executing something after or before running a `bundle package`?

**Comment by andremedeiros** [comment]
It should do that, yes, particularly for the install/update commands.

**Comment by tf** [comment]
Just as an aside: Given the proposed gem naming scheme of `bundler-something`, one should probably consider introducing a conventional plugin namespace like `Bundler::Plugins::Something` the [way resque did](https://github.com/resque/resque/blob/master/docs/PLUGINS.md). Otherwise there is the risk of namespace collisions - especially since `bundle gem bundler-something` defaults to creating `lib/bundler/something.rb`.

Maybe there could even be a special `--bundler-plugin` option for the `bundle gem` command to make following such conventions easy.

**Comment by agis-** [comment]
@maclover7 Is this still relevant now that https://github.com/bundler/bundler/pull/3030 is merged?

**Comment by maclover7** [comment]
I'd say we need something more robust than that (although it's a good start). Let's keep this open until https://github.com/bundler/bundler/pull/3807 or something along those lines gets merged.

**Comment by LynnCo** [comment]
See also this issue: https://github.com/bundler/bundler-features/issues/8 (it's a bit long)
