### ISSUE TITLE
2.0: a whole new world

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4856]
- [x] remove psyched_yaml https://github.com/bundler/bundler/issues/4825 https://github.com/bundler/bundler/pull/4916
- [x] remove .ruby-version support #4892 
- [x] remove `inject` command (deprecated in favor of `add`)
- [x] always resolve with auto-lock to RUBY_VERSION (as per #4853)
- [x] in --deployment mode, raise when running ruby doesn't match auto-locked ruby
- [x] documentation for managing ruby versions with bundler
- [x] remove --binstubs from the docs (code already removed)
- [x] default to only installing newer versions during `update` https://github.com/bundler/bundler/issues/4511 https://github.com/bundler/bundler/pull/4893
- [x] default to `cache --all-platforms` and remove flag #4918 
- [x] merge in Tim's spec for source issues https://github.com/bundler/bundler/pull/3696
- [x] merge in 1.13
- [x] merge in 1.14
- [x] take over master
- [x] ~enable trampolining to locked versions "~> 1"~

**Comment by segiddins** [comment]
the pre-req for all of this work is for master to be merged back to development (again)
