### ISSUE TITLE
Tasks anyone can claim

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4871]
- [x] resurrect the unfinished `add` command #4901
- [ ] store a Gemfile checksum in Gemfile.lock, so we can skip the resolver when unchanged
- [x] Add a `bundle issue` command that prints instructions for reporting issues as well as the output from `env` and `doctor` #5505
- [x] add `--parsable` option to `config` #4913 https://github.com/bundler/bundler/issues/4919 #5306
- [x] fix build and merge OpenSSL version for `env` https://github.com/bundler/bundler/pull/4624
- [x] on gem install errors, print the last ten lines of make output if possible
- [x] parse settings keys on "." first so keys are always accurate https://github.com/bundler/bundler/issues/4830
- [x] setting to only install newer options during `update` https://github.com/bundler/bundler/issues/4511, https://github.com/bundler/bundler/pull/4893
- [x] Refactor RSpec matchers into proper classes https://github.com/bundler/bundler/issues/4806
- [x] Use `/tmp/bundler` for compact_index when Dir.home isn't writable https://github.com/bundler/bundler/issues/4792 #4819
- [x] Skip persisting global settings to disk if Dir.home is missing or unwritable #4918 
- [x] Fix running bundler/inline blocks twice https://github.com/bundler/bundler/issues/4837
- [ ] add support for the compact index to [Gemstash](https://github.com/bundler/gemstash)
- [x] Address comments and merge symlink support for standalone bins https://github.com/bundler/bundler/pull/4782
- [x] Retry downloading gems https://github.com/bundler/bundler/issues/4846
- [x] Refactor Definition to avoid `eval`ing Gemfile twice https://github.com/bundler/bundler/pull/4417 #4952
- [ ] Run Travis specs in parallel using `parallel_tests` https://github.com/bundler/bundler/pull/4345
- [x] Write an RFC for and/or implement a fix for  `platform`, which today means multiple conflicting things: gem architecture (eg x86_64), gem platform OS (eg java), engine version (eg mri_22). This may involve adding gemspec support for Ruby engine and version requirements?
- [x] Rebase and merge resolver-style errors for Ruby version conflicts https://github.com/bundler/bundler/pull/4654
- [ ] Add a `bundle plugin list` command to list the current plugins in the bundle. #5467 
- [ ] Add a `bundle plugin update` command to update the version of an installed plugin #5446
- [ ] Fix vendored git gems not being updated on `bundle update` #5423 #5398
- [x]  Document why bundle exec updates the Gemfile.lock #5245

never say I didn't give you things you could do, @segiddins :grin:

**Comment by JuanitoFatas** [comment]
I would like to work on #4913

**Comment by indirect** [comment]
@JuanitoFatas sounds great. once you send a PR, come back and check it off. 😁

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas sounds great. once you send a PR, come back and check it off.

Hi! I think check is only available for collaborator, not for contributor, but I link the PR back, so you can check it off when you revisit this issue :)

**Comment by JuanitoFatas** [comment]
#4846 merged, can check it off.

**Comment by colby-swandale** [comment]
updated status of this board

**Comment by prog1dev** [comment]
@indirect Is it worth of working on this request?
```
store a Gemfile checksum in Gemfile.lock, so we can skip the resolver when unchanged
```
Looks like in `Bundler::Definition` there is some kind of caching already and this is unnecessary to implement

**Comment by segiddins** [comment]
I've done some experimental work on that one, @prog1dev

**Comment by colby-swandale** [comment]
I'm closing this issue, we've replaced this list with the [help wanted](https://github.com/bundler/bundler/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) and [good first issue](https://github.com/bundler/bundler/labels/good%20first%20issue) Github tags.

**Comment by hmistry** [comment]
@colby-swandale I think this list was good to have for those looking to contribute. Having multiple paths to discover issues to work on caters to different ways people look to find info. To me this list was a much easier way to find a list of issues to work on and it's a good central way to track and prioritize what needs to be worked on.

I highly recommend reviving it by making a new version since 3/4's of this is done. Also keep the Github tags as another method to find things to work on.
